### ISSUE TITLE
Bug: Ping and Jitter routes not working as expected

### ISSUE THREAD

**Issue by sachdeva-shrey** [bench-routes/bench-routes#348]
**Describe the bug**
The `/ping` and `/jitter` routes do not display the charts upon selecting the routes from the input.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `/ping` or `/jitter`. You can navigate from Testing Tools in the sidebar menu.
2. Select a route from the select input.
3. No charts/information is displayed.
4. See error: `index.js:1451 SyntaxError: Unexpected token I in JSON at position 0` in the console.

**Expected behaviour**
The Ping/Jitter charts should be displayed for the selected route.

**Screenshots**
![Screenshot from 2021-03-13 18-15-42](https://user-images.githubusercontent.com/47667325/111063038-8f78f680-84d2-11eb-98ca-5e8dc7a4a9eb.png)

**Desktop:**
 - OS: Ubuntu
 - Version 20.04

**Comment by geforce6t** [comment]
I think this might be due to incorrect url requested for the resonse. 
![Screenshot from 2021-03-13 19-44-07](https://user-images.githubusercontent.com/63119158/111063746-76724480-84d6-11eb-8e03-f72a3295f59a.png)

in the file JitterModule.tsx a request is made like this: 
const response = await fetch(
        `${HOST_IP}/query?timeSeriesPath=storage/jitter/chunk_jitter_${res}`
      );

here `res` is the domain name of the url, but inside my storage directory no such file exist,
most of the files seem to end with a hash like : chunk_jitter_718253293.json, if the `res` variable is changed to these end 
hash values then the output is desirable. I am not pretty sure but this might be the cause of this bug?

**Comment by geforce6t** [comment]
I'll fix this if no-one is doing

**Comment by Tushar3099** [comment]
@muskankhedia  I have confusion about the implementation of @geforce6t as what he is doing is fetching all the time series data from the backend, then finding the one that matches the URL, and send its specific jitter hash.
Won't it be very time-consuming with lots of time-series data?
I am not sure, but since we require the hash to find the route-time-series path, we can make the hash for the route and find the path. This will reduce the time of searching the URL in all time-series data.
But as I went through the code, I learned that for making the hash of a route, we need its `{URL, body, header, params, method}`, all of which are not provided by the user.
What should be the optimal way to do it?

**Comment by geforce6t** [comment]
> I am not sure, but since we require the hash to find the route-time-series path, we can make the hash for the route and find the path. This will reduce the time of searching the URL in all time-series data.

I don't think this can be done from the frontend, all we can do is the api call, so **if** this fetching all the time series is time-consuming what can be done is an endpoint to return the hash against the route which can be send dynamically from the url , but this can be a problem as the route url contains "/" which can cause problem as it will separate the different parts of the route, maybe this is why only the domain name was being send before in these api calls.

**Comment by Tushar3099** [comment]
@geforce6t Obviously these changes are to be done in the backend as there are already functions `URLHash` for making hash for a URL (any legit URL) but as I said it would require `body,header,params,method` fields also which is not provided by the frontend.Hence that causes a problem.

**Comment by muskankhedia** [comment]
@Tushar3099 you are correct. Solving this issue requires the implementation of a new API in the backend, also as you said all the required data aren't from the frontend, all the required APIs needs to be implemented in the backend to solve it.

**Comment by geforce6t** [comment]
@muskankhedia sorry for the confusion, can you please explain what that new api will do ? will it return the hash of the route we put as a parameter in this new api call so that later on we can put that hash here : `${HOST_IP}/query?timeSeriesPath=storage/jitter/chunk_jitter_${hash}` and get the result?

**Comment by muskankhedia** [comment]
@geforce6t we could have done that but the issue is, for now, the data we have in the frontend is `URL` but the params required to create the `URLHash` are `body,header,params,method, URL` so now things needs to be changed from the base level as either we now require all the data beforehand in the frontend or again go through the loop to find the URL details from the `local-config.yaml` file using the URL. I personally don't feel the second option be good in the long run as when we have thousands of routes this won't be a preferable solution.

@Harkishen-Singh What are your views on this?

**Comment by Tushar3099** [comment]
@geforce6t 
IMHO I think that the same API `/query` can be modified so that it can find the hash of the given route in the backend and fetch the file accordingly and do the rest as it is.
In that case no change in frontend would be required.
But my doubt stuck in the same place, finding hash requires more data than just the URL.
@muskankhedia Can you please explain the utility of this Testing window. What specific task does it accomplishes?
If we just want the hash for all the monitored routes IMHO we can fetch all the monitored routes before loading the screen.

**Comment by geforce6t** [comment]
@Tushar3099 can you please explain one thing..  So in the `main.go` a goroutine is spun in the beginning of the program which is responsible for adding routes (added to the local config file)to the `matrix` (map) , then through a loop every new entry gets added to the map with the `hash`(generated) as the key and the `structure pointer` (with detail about the route) as the value, now since this `matrix` map is a pointer can't we just loop through it and get the hash for the required url? so how will finding hash require more than just url?

**Comment by Tushar3099** [comment]
@geforce6t Finding hash through looping over all routes is not the solution. That's the same thing as fetching all the routes in frontend and matching the one with same URL.
I was talking about generating the URL for the route for which a function `URLHash` is already there.But the function requires other fields also like `header,params,method` .

**Comment by muskankhedia** [comment]
> @geforce6t
> IMHO I think that the same API `/query` can be modified so that it can find the hash of the given route in the backend and fetch the file accordingly and do the rest as it is.
> In that case no change in frontend would be required.
> But my doubt stuck in the same place, finding hash requires more data than just the URL.
> @muskankhedia Can you please explain the utility of this Testing window. What specific task does it accomplishes?
> If we just want the hash for all the monitored routes IMHO we can fetch all the monitored routes before loading the screen.

@Tushar3099 You can either make modifications to the existing API or create a new one. The tasks section seems similar to the Monitoring section but the monitoring section makes the work a lot difficult when the user wants to check only Ping or Jitter values of multiple routes which is easily handled in the tests section. Tests section ease the navigation between routes when the user wants to check only either `Ping` or `Jitter` values of different routes.

**Comment by Harkishen-Singh** [comment]
@muskankhedia I was in an initial impression that doing a two-times communication with the API is not a good thing. But it turns out that UI needs to know some way which all paths are available for querying. This will require the first request and I don't think we can avoid it.

So, as far as we fetch the updated list of all time-series (from `/get-route-time-series` endpoint), and then fill them in the dropdown and let the user click and on click, we send the particular hash to the querier; it should be fine. It will take a lot of time only if we loop across all the time-series or response of the above endpoint. But I am under the impression that we just show that in the dropdown and ask the user to click on the one he is interested in. As long as this happens, I don't think there would be any slower. (only time involved would be fetching the updated list of all routes from the endpoint which should be fast).

I haven't gone thought the PR yet, but I hope to do it this weekend. Thank you guys for the discussion and your patience.

**Comment by Tushar3099** [comment]
@Harkishen-Singh I was also suggesting the same solution.Shall I make a PR for that?

**Comment by Harkishen-Singh** [comment]
I think @geforce6t is already working on this. I will let him for this issue. I haven't gone through the PR, but there can be better possibilities than what I proposed.

**Comment by Tushar3099** [comment]
Thanks for the reply @Harkishen-Singh will work on other issues then.
