### ISSUE TITLE
Bug: empty white box in quick input page in dark mode

### ISSUE THREAD

**Issue by iamkryptonite** [bench-routes/bench-routes#393]
**Describe the bug**
In dark mode if we go to quick input and click on body(or header/params) we see a white empty box.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'quick input page' ans turn on dark mode
2. Click on 'body'
3. See error

**Expected behaviour**
The color of the box should the match the color of the rest of the page in both dark/light mode.

**Screenshots**
![Screenshot from 2021-03-19 19-11-08](https://user-images.githubusercontent.com/43510609/111789899-a743e680-88e7-11eb-8f0f-cc703b3948bc.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by iamkryptonite** [comment]
I would like to work on this if approved.

**Comment by Tushar3099** [comment]
Actually, that's not weird @iamkryptonite, the problem is that in dark mode, the text color is changed to white and the JSONfied response box doesn't change its background which results in an empty white box.
![Screenshot from 2021-03-19 20-11-16](https://user-images.githubusercontent.com/51849085/111798018-ad3dc580-88ef-11eb-8ec0-097e110704bc.png)
As you can see that when I selected the text it's there, so we just have to toggle color appropriately for this issue.

**Comment by iamkryptonite** [comment]
> Actually, that's not weird @iamkryptonite, the problem is that in dark mode, the text color is changed to white and the JSONfied response box doesn't change its background which results in an empty white box.
> ![Screenshot from 2021-03-19 20-11-16](https://user-images.githubusercontent.com/51849085/111798018-ad3dc580-88ef-11eb-8ec0-097e110704bc.png)
> As you can see that when I selected the text it's there, so we just have to toggle color appropriately for this issue.
> 
Correct!
